services:
  - type: cron
    name: ping
    env: docker
#    branch: main
    schedule: 0/1 * * * * # interval at which the job should run
    dockerCommand: RUN ping -c 3 https://mypublicapi-webservice.onrender.com # command to run
